resolver: lts-13.23

build:
  copy-bins: true

# Local packages, usually specified by relative directory name
packages:
  - '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
  - algebraic-graphs-0.2
  - bloomfilter-2.0.1.0
  - bound-2
  - cacophony-0.10.1
  - compactable-0.1.2.2
  - lz4-0.2.3.1
  - monad-gen-0.3.0.1
  - prelude-extras-0.4.0.3
  - unagi-chan-0.4.0.0
  - katip-0.6.3.0
  - FloatingHex-0.4
  - git: git@github.com:kadena-io/pact.git
    commit: f42a48fad4f1b2abd554f3a7c2514239666bebeb
  # - /Users/marklnichols/dev/pdev/pact-3-kadena/pact
  # - /home/mark/dev/pdev/pact-3-kadena/pact

  - git: git@github.com:kadena-io/pact-persist.git
    commit: 21760a2b590e5e76ded6d89222607d286fecfb32

  - git: https://github.com/abbradar/hdbc-odbc.git
    commit: 79ffd1f5060d2c8b5cbdfd4eba8ae6414372d6b7

  # --- The following copied from Pact's stack.yaml --- #
  # --- Missing from Stackage --- #
  - ed25519-donna-0.1.1
  - prettyprinter-convert-ansi-wl-pprint-1.1

  # --- Forced Downgrades --- #
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2  # Due to megaparsec 7

  # --- Forced Upgrades --- #
  - sbv-8.2

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9


local-bin-path: ./bin
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
