resolver: lts-6.12

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/slpopejoy/snap-cors.git
    commit: cc88bab1fd3f62dc4d9f9ad81a231877a639c812
  extra-dep: true
- location:
    git: git@bitbucket.org:spopejoy/pact.git
    commit: 045ead5ca8b8cb98dc26a6cda1c061d337ca9440
  extra-dep: true
- location:
    git: git@bitbucket.org:spopejoy/pact-persist.git
    commit: 3d6925ed7f2044923b0ef4ab8fc2912aab07bebe
  extra-dep: true
- location:
    git: https://github.com/abbradar/hdbc-odbc.git
    commit: 79ffd1f5060d2c8b5cbdfd4eba8ae6414372d6b7
  extra-dep: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- cacophony-0.8.0
- cryptonite-0.16
- ed25519-donna-0.1.1
- kan-extensions-5.0.1
- lens-4.13.2.1
- lz4-0.2.3.1
- megaparsec-4.2.0
- safe-exceptions-0.1.4.0
- unagi-chan-0.4.0.0
- trifecta-1.6

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
