# Retrives the sqlite and log files produced by Kadena Servers

- name: Run Load Test
  hosts: localhost
  tasks:
    - name: Clean up result directory (if it exists)
      file:
        path: /home/ubuntu/result/
        state: absent

    - name: Create result directory
      file:
        path: /home/ubuntu/result/
        state: directory
        owner: ubuntu
        mode: 0755
    
- name: Fetch Kadena Servers' log files
  hosts: tag_Name_kadena_server
  become: True
  gather_facts: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - synchronize:
        src: /home/ubuntu/log/*sqlite
        dest: /home/ubuntu/result/{{ hostvars[inventory_hostname].ec2_private_ip_address }}-log/
        mode: pull
    - synchronize:
        src: /home/ubuntu/log/*log
        dest: /home/ubuntu/result/{{ hostvars[inventory_hostname].ec2_private_ip_address }}-log/
        mode: pull
