### (Re)start Kadena Servers

- name: Clean up Kadena Server(s)
  hosts: tag_Name_kadena_server
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
    - name: Identify Thread Running Kadena Server (if running)
      shell: pgrep kadenaserver
      register: server_thread
      ignore_errors: yes

    - name: Terminate Kadena Server Thread (if running)
      become: True
      command: kill "{{ server_thread.stdout }}"
      when: "server_thread.stdout"

    - name: Remove Kadena server logs
      file: 
        path: "{{ item }}"
        state: absent
      with_items:
          - "/home/ubuntu/log/*.sqlite*"
          - "/home/ubuntu/log/*.log"

    - name: Create necessary log files
      file:
        path: "{{ item }}"
        state: touch
        owner: ubuntu
      with_items:
        - "/home/ubuntu/log/access.log"
        - "/home/ubuntu/log/error.log"
        - "/home/ubuntu/log/node.log"

- name: Start Kadena Servers
  hosts: tag_Name_kadena_server
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: True
  tasks:
    - shell: ./kadenaserver +RTS -N4 -RTS -c conf-cluster.yaml 2>&1 | tee -a log/node.log && sleep 1
      async: 1200
      poll: 0
      register: active_servers
    - pause:
        seconds: 2
