# Runs the AWS Kadena load test

- name: Run Load Test
  hosts: localhost
  vars:
    total: 120
    size: 5   
  tasks:
    - name: Create result directory
      file:
        path: /home/ubuntu/result/
        state: directory
        owner: ubuntu
        mode: 0755
    
    - name: Clean up result directory
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - /home/ubuntu/result/*
 
    - name: Make Bolosim Executable
      file:
        path: /home/ubuntu/kadena-beta/bin/ubuntu-16.04/bolosim
        mode: a+x

    - name: Run Bolosim Test
      command: rlwrap -A /home/ubuntu/kadena-beta/bin/ubuntu-16.04/bolosim --transactions={{ total }}  --batchsize={{ size }} --norunserver --configfile=client.yaml --dirforconfig=/home/ubuntu/conf/
      args:
        chdir: /home/ubuntu/kadena
      register: result

    - name: Write Result of Bolosim Load Test to File
      copy: content={{ result.stdout }} dest=/home/ubuntu/result/result.log

- name: Fetch Kadena Servers' log files
  hosts: tag_Name_kadena_server
  become: True
  gather_facts: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - copy:
        src: /home/ubuntu/log/*
        dest: /home/ubuntu/result/log-{{ inventory_hostname }}/
        remote_src: yes
