### Create EC2 Instances and Node Configurations

- name: Spin up EC2 Instances
  hosts: localhost
  gather_facts: True
  vars:
    type: t2.micro
    # the kadena-ubuntu-base image
    image: ami-03210f1c8a84ba9c0
    security: kadena_beta
    region: us-west-2
  tasks:
    - name: Launch Kadena Server Instances
      ec2:
        key_name: wizard-example-key
        group: "{{ security }}"
        instance_type: "{{ type }}"
        image: "{{ image }}"
        wait: true
        wait_timeout: 500
        region: "{{ region }}"
        monitoring: no
        instance_tags:
          Name: kadena_server
        exact_count: 4
        count_tag:
          Name: kadena_server
      register: ec2_servers_out

    - name: Add Instances to 'kadena_all' Host Group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: kadena_all
      with_items: 
        - "{{ ec2_servers_out.instances }}"

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items:
        - "{{ ec2_servers_out.instances }}"

- name: Create node configurations
  hosts: localhost
  vars:
    ipList: "{{ ec2_servers_out.instances }}"
  tasks:
    - name: Create 'conf' directory to store nodes' configuration file 
      file:
        path: /home/ubuntu/conf/
        state: directory
        mode: 0755

    - name: Clean up Configuration Files
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - /home/ubuntu/conf/*
        - /home/ubuntu/ipAddr.yml 
    
    - name: Create file of Kadena server(s)' IP addresses
      template:
        src: /home/ubuntu/kadena/scripts/aws/ipAddr.j2
        dest: /home/ubuntu/ipAddr.yml
        mode: 0777

    - name: Generate the node configuration for the Kadena servers
      shell: yes '' | /home/ubuntu/kadena-beta/bin/ubuntu-16.04/genconfs --distributed /home/ubuntu/ipAddr.yml
      args:
        chdir: /home/ubuntu/

- name: Configure instance(s)
  hosts: kadena_all
  become: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: False
  tasks:
    - name: Create log directory in server nodes
      file:
        path: /home/ubuntu/log/
        state: directory
        owner: ubuntu
        mode: 0755

    - name: Copy node conf file to server
      copy:
        src: /home/ubuntu/conf/{{inventory_hostname}}-cluster.yaml
        dest: /home/ubuntu/conf-cluster.yaml
        owner: ubuntu

    - name: Copy `kadenaserver` executable to server
      copy:
        src: /home/ubuntu/kadena-beta/bin/ubuntu-16.04/kadenaserver
        dest: /home/ubuntu/kadenaserver
        owner: ubuntu
        mode: a+x

- name: Refresh Inventory
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Refresh EC2 cache
      command: /etc/ansible/ec2.py --refresh-cache
    - name: Refresh in-memory EC2 cache
      meta: refresh_inventory
